name: Deploy Application

on:
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
          
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 65.0.52.55
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          source: "app/*"
          target: /home/ubuntu/app/
          rm: true

      - name: Deploy Application
        uses: appleboy/ssh-action@v1
        with:
          host: 65.0.52.55
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/app/ &&  task deploy_app
            sleep 10
